install rails

diff --git a/bin/add-ruby b/bin/add-ruby
--- a/bin/add-ruby
+++ b/bin/add-ruby
@@ -1,6 +1,6 @@
 #!/bin/sh
 # Prompt the user for the new Ruby version
-read -p "Enter new Ruby version: " ruby_version
+read "Enter new Ruby version: " ruby_version
 
 # Determine the rubies installation directory.
 # Defaults to $HOME/.rubies if RUBIES_INSTALL_ROOT is not set.
@@ -29,4 +29,18 @@ if sed -E "s|^chruby[[:space:]]+.*$|chruby 3.4.2|" ~/.extras > "$tmpfile"; then
 else
   echo "Failed to update ~/.extras"
   rm "$tmpfile"
+fi
+
+. /Users/daviddegroot/.zshrc
+
+read "Would you like to install rails? Y/n" install_rails
+
+if [ "$install_rails" = "Y" ] || [ "$install_rails" = "y" ]; then
+  echo "Installing Rails..."
+  if ! gem install rails; then
+    echo "Rails installation failed. Exiting."
+    exit 1
+  fi
+else
+  echo "Skipping Rails installation."
 fi
